### ISSUE TITLE
Build KO because of node-sass

### ISSUE THREAD

**Issue by alustrement** [themotleyfool/Klondike#174]
Any workaround for this ?

> node-sass@2.1.1 install C:\Sandbox\Klondike\node_modules\broccoli-sass\node_modules\node-sass
> node scripts/install.js
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-4.6/binding.node
> node-sass@2.1.1 postinstall C:\Sandbox\Klondike\node_modules\broccoli-sass\node_modules\node-sass
> node scripts/build.js
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Sandbox\Klondike\node_modules\broccoli-sass\node_modules\node-sass\node_modules\pangyp\lib\install.js:403:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Sandbox\Klondike\node_modules\broccoli-sass\node_modules\node-sass\node_modules\pangyp\node_modules\request\request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:433:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Sandbox\\Klondike\\node_modules\\broccoli-sass\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp" "rebuild"
gyp ERR! cwd C:\Sandbox\Klondike\node_modules\broccoli-sass\node_modules\node-sass
gyp ERR! node -v v4.6.1
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok
Build failed

**Comment by ludovicperrier** [comment]
Hello,
I try to build since 3 days with lots of config of npm and node but always there is an error. I pass libsass problem but I have another error.

Someone have a config to build today on windows 10?
Regards
