### ISSUE TITLE
The package file could not be loaded. ---> System.InvalidOperationException: already has a dependency defined for 'NETStandard.Library'.

### ISSUE THREAD

**Issue by Ashtonian** [themotleyfool/Klondike#176]
Tried loading a recent automapper package in klondike and its not working. The version doesn't show up in the UI or feed and the log shows the following error: 

```code
The package file 'automapper.5.0.2.nupkg' could not be loaded. ---> System.InvalidOperationException: 'AutoMapper' already has a dependency defined for 'NETStandard.Library'.
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.Lucene.FastZipPackage.ProcessManifest(Stream manifestStream)
   at NuGet.Lucene.FastZipPackage.Open(String fileLocation, Stream stream, Byte[] hash)
   at NuGet.Lucene.FastZipPackage.Open(String fileLocation, IHashProvider hashProvider)
   at NuGet.Lucene.LucenePackageRepository.LoadFromFileSystem(String path)
   at NuGet.Lucene.PackageIndexer.<SynchronizePackage>d__40.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Lucene.PackageIndexer.<SynchronizePackage>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Lucene.PackageIndexer.<SynchronizeIndexWithFileSystemAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Lucene.PackageIndexer.<SynchronizeIndexWithFileSystemAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Lucene.Web.Startup.<>c__DisplayClass21_0.<<StartIndexingIfConfigured>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Lucene.Web.Util.TaskRunner.Invoker.<Invoke>d__3.MoveNext()
```

**Comment by Ashtonian** [comment]
Sorry - thought I was running latest. This issue seems to have been resolved in the latest version.
