### ISSUE TITLE
Mirroring with introduction of HTTPS redirection on NuGet.org

### ISSUE THREAD

**Issue by mindriven** [themotleyfool/Klondike#186]
Hi @chriseldredge 
Packages mirroring stopped working for me :-( for some reason. I have strong suspicion that that's because introduction of https redirection nuget.org, see here: http://blog.nuget.org/20170119/nuget-end-of-xp-support.html

I've added the 's' to the mirror server url like this:
`<add key="packageMirrorTargetUrl" value="https://www.nuget.org/api/v2/" />`
and now Klondike logs look as pasted below.
Can you please let me know if you're planning to react to this change and support https? Or am I completely wrong and the problem does not lay on Klondike at all?

Thanks in advance

`2017-01-26 15:43:25,928 ERROR  9 MirroringPackageRepository FindPackagesByIdInOrigin Exception on FindPackagesById('SharpZipLib') for package origin https://www.nuget.org/api/v2/: An error occurred while loading packages from 'https://www.nuget.org/api/v2/': The ServicePointManager does not support proxies with the https scheme.
System.InvalidOperationException: An error occurred while loading packages from 'https://www.nuget.org/api/v2/': The ServicePointManager does not support proxies with the https scheme. ---> System.NotSupportedException: The ServicePointManager does not support proxies with the https scheme.
   at System.Net.ServicePointManager.FindServicePointHelper(Uri address, Boolean isProxyServicePoint)
   at System.Net.HttpWebRequest.FindServicePoint(Boolean forceFind)
   at System.Net.HttpWebRequest.set_Proxy(IWebProxy value)
   at NuGet.RequestHelper.ConfigureRequest(HttpWebRequest request)
   at NuGet.RequestHelper.GetResponse()
   at NuGet.HttpClient.DownloadData(Stream targetStream)
   at NuGet.DataServiceContextWrapper.GetDataServiceMetadata(Uri metadataUri)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean absoluteExpiration)
   at NuGet.DataServiceContextWrapper.get_ServiceMetadata()
   at NuGet.DataServiceContextWrapper.SupportsServiceMethod(String methodName)
   at NuGet.DataServicePackageRepository.FindPackagesById(String packageId)
   --- End of inner exception stack trace ---
   at NuGet.DataServicePackageRepository.FindPackagesById(String packageId)
   at NuGet.Lucene.Web.Models.MirroringPackageRepository.FindPackagesByIdInOrigin(String id)`

**Comment by Johlandabee** [comment]
Any news on thins?
