### ISSUE TITLE
500 error on 'Illegal' version string

### ISSUE THREAD

**Issue by icarr-fsg** [themotleyfool/Klondike#189]
Attempting to restore a solution which references swashbuckle.aspnetcore causes a 500 error to be returned from klondike. This aborts the Visual studio build process requiring the Klondike package source to be removed to continue.

The problem appears to relate to a version of this package with a tag: 1.0.0--rc1 (Note double hyphen)

The failing URL is:

http://nuget-klondike:8080/api/odata/FindPackagesById()?id=%27Swashbuckle.AspNetCore%27
 
Stack trace:

2017-04-26 14:40:19,593 ERROR  65 UnhandledExceptionLogger HandleAsync Unhandled exception: System.ArgumentException: '1.0.0--rc1' is not a valid version string.
Parameter name: version
System.ArgumentException: '1.0.0--rc1' is not a valid version string.
Parameter name: version
   at NuGet.SemanticVersion.Parse(String version)
   at NuGet.DataServicePackage.NuGet.IPackageName.get_Version()
   at NuGet.PackageEqualityComparer.<.cctor>b__1(IPackageName x)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<UnionIterator>d__66`1.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
...

**Comment by icarr-fsg** [comment]
Note: the project references 1.0.0 (not 1.0.0--rc1) and I can't find any other reference to the 'invalid' version.

**Comment by m-wilczynski** [comment]
For posteriority: Klondike seems to not support new versions of NuGet which is the root cause for many versioning issues (due to support for .NET Standard 2.0, semantic versioning etc.).

**Comment by mkurz01** [comment]
Had this error, too.
This works:
NuGet.exe install Swashbuckle.AspNetCore -Source https://packages.nuget.org/v1/FeedService.svc/
This works not:
NuGet.exe install Swashbuckle.AspNetCore -Source http://localhost:8080/api/odata
