### ISSUE TITLE
SymbolsSource throws NullReferenceException

### ISSUE THREAD

**Issue by hkaushik** [themotleyfool/Klondike#65]
Hi
I have Klondike set up and running as packages repository. I'm trying to get SymbolSource working.

After uploading packages there was no folder created as Symbols folder inside ~App_Data/ folder. But I looked at the packages folder and it has both Lib (.pdb file) and src (containing .cs files) in .nupkg.
On Klondike UI I always get message that "Symbols and source code are not available for this package. " while clicking Package link.

When I am trying to access /api/symbols address I get following exception.
(microdata object: http://localhost:9000/api/schema/System.Web.Http.HttpError) MessageAn error has occurred. ExceptionMessageObject reference not set to an instance of an object. ExceptionTypeSystem.NullReferenceException StackTrace at NuGet.Lucene.Web.Symbols.SymbolSource.OpenFile(String relativePath) at NuGet.Lucene.Web.Controllers.SymbolsController.GetFile(String path) at lambda_method(Closure , Object , Object[] ) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__0.MoveNext() 

I have already setup my visualStudio pointing to my Symbol Server and have installed debug tool. Setup appsetting in web config file.
Am I doing something wrong here.

**Comment by chriseldredge** [comment]
This is on Klondike 1.6.2? It sounds like the problem is that pushing symbol packages is not detecting the package as a symbol package.

**Comment by hkaushik** [comment]
I have downloaded code from here;
https://github.com/themotleyfool/Klondike

is there any latest version after this?

**Comment by chriseldredge** [comment]
The latest code is in the `self-host` branch https://github.com/themotleyfool/Klondike/tree/self-host

This will be the next release, but I haven't tested it in production anywhere yet.

**Comment by hkaushik** [comment]
Thanks!
I downloaded 1.6.2 release version and still not seeing the symbols...
I will explain steps what I am doing:
1> I have setup a Klondike repository Server and it has App.1.0.90.nupkg and App.1.0.90.symbols.nupkg
2> I have a website setup (in IIS) at my machine (release 1.6.2). I used Klondike UI (Api->Get Package) to get the packages from my remote Klondike repository Server. App.1.0.90.nupkg is downloaded in ~/App_Data/Package folder but it looks like it is Symbols as it has both Lib and src.

Still, I see the message "Symbols and source code are not available for this package. " on UI.
Am I doing something wrong. Why I dont see anything called ~/App_Data/Symbols on my local machine after getting the package.
I setup local machine as I do not want to install Debugging tool on remote server.

**Comment by hkaushik** [comment]
And when will you have Release version ready for self-host branch https://github.com/themotleyfool/Klondike/tree/self-host
?

**Comment by chriseldredge** [comment]
Not sure on timeline for next release.

Please try clearing the log file in ~/App_Data/Logs, then push your symbol package and attach the log after that completes.

Have you installed the Debugging Tools for Windows and configured them in App.config / Settings.config?

**Comment by hkaushik** [comment]
Not sure what do you mean "push your symbol package". I use Ember front-end for private package hosting. I go to API->Get Package and I specify my ID and version. How can I push Symbol packages using Ember front-end? may be I am misunderstanding something...

**Comment by hkaushik** [comment]
I issued the following command:
NuGet Push C:\Klondike-Release-1.6.2\App_Data\Packages\App.1.0.90.symbols.nupkg 9719fd21-a080-409a-beb0-884df0413813 -Source http://klondike.latest.release/api/symbols

And I got the following exception in Log file:
2015-01-15 16:54:10,636 ERROR  321 UnhandledExceptionLogger OnExceptionAsync Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Lucene.Web.Symbols.SymbolSource.OpenFile(String relativePath)
   at NuGet.Lucene.Web.Controllers.SymbolsController.GetFile(String path)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2015-01-15 16:54:10,637 ERROR  321 UnhandledExceptionLogger OnExceptionAsync Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Lucene.Web.Symbols.SymbolSource.OpenFile(String relativePath)
   at NuGet.Lucene.Web.Controllers.SymbolsController.GetFile(String path)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

**Comment by chriseldredge** [comment]
Ah, I think I understand the problem now. While it's true you should have Visual Studio use http://klondike.latest.release/api/symbols to download symbols, in Klondike 1.6.2, the symbol package should be pushed to the same place you would push normal package (http://klondike.latest.release/api/)

**Comment by hkaushik** [comment]
You are rock star:)
That worked..I got the symbols oushed to my Symbols folder and now I see "000Admin", "App", "App.pdb" folder and pingme text file.
I can see message on UI that "Symbols and source code are available for this package." and "Some packages already have symbols. Debug away! "
But I still see the same exception of System.NullReferenceException: Object reference not set to an instance of an object. while browsing http://klondike.latest.release/api/symbols.
And when I try to debug in VS I still get prompt that open the source file location to debug.
Am I still missing something?

**Comment by chriseldredge** [comment]
The endpoint http://klondike.latest.release/api/symbols expects a file path to be appended, in the form of `GET /api/symbols/{path}`, and in v1.6.2 there is a bug when no additional file path is provided. It should return a 400 Bad Request but generates an exception instead.

This endpoint is not intended for browsing; it is intended to serve symbol files to Visual Studio or WinDbg.

**Comment by hkaushik** [comment]
Just curious that what is the path..I tried giving the relative path..absolute path of my symbol folder but that does not work..

**Comment by chriseldredge** [comment]
It maps paths relative to the App_Date/Symbols folder. Try e.g. http://klondike.latest.release/api/symbols/000Admin/history.txt

**Comment by hkaushik** [comment]
Symbols are working great. I really appreciate your help:)
I just want to share one of my experience of Symbols. If I create Klondike private repository (klondike.latest.release website) on my local machine and push Symbol packages, configure VS to http://klondike.latest.release/api/symbols it really does not create App.pdb, src folders in Symbolcache folder. It may be it is local. But it creates every required folder on my Symbolcache folder if I configure my VS to my Remote Klondike Private Symbol server.
Thanks once again for your kind help!
Thank you Kindly!

**Comment by chriseldredge** [comment]
Glad you got it working and that's an interesting behavior you spotted with VS.
